version: "3.0"

services:
  application:
    build: .
    restart: always
    image: haredev/library-web-application:latest
    container_name: library-web-application
    ports:
      - "8080:8080"
    depends_on:
      - mysql-database

  mysql-database:
    image: "mysql:8.0.30"
    restart: always
    container_name: 'library-web-application-database'
    ports:
    - "9999:9999"
    environment:
      MYSQL_DATABASE: library-database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin

