version: "3.8"
services:
  backend-spring-boot:
    build:
      context: .
    container_name: library-spring-boot
    image: haredev/library-web-application:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database-postgres:5555/postgres
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    ports:
      - "9090:9090"
    networks:
      - spring-boot-postgres
    depends_on:
      database-postgres:
        condition: service_healthy
    restart: on-failure

  database-postgres:
    image: postgres:14.5
    container_name: library-postgresql
    networks:
      - spring-boot-postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DATABASE=postgres
    volumes:
      - database-data:/var/lib/postgresql
    ports:
      - "5555:5555"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  spring-boot-postgres:
volumes:
  database-data: