# Application DEV - profile properties

server:
    port: 8181
  
  # Spring-Boot with H2 Database Configuration

spring:
  h2:
    console:
      enabled: true
      path: /dev-test-h2
  datasource:
    path: /dev-test-h2
    url: jdbc:h2:mem:test-h2
    driverClassName: org.h2.Driver
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}

  # JPA Configuration

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
      format_sql: true
  database-platform:
    org.hibernate:
      dialect: H2Dialect
  
  # Swagger UI

springdoc:
  swagger-ui.path: swagger-ui.html
  packagesToScan: com.haredev.library
  swagger-ui:
    enabled: true