# Application DEV - profile properties

server:
    port: 8181
  
  # Spring-Boot with H2 Database Configuration

spring:
  h2:
    console:
      enabled: true
      path: /dev-test-h2
  datasource:
    path: /dev-test-h2
    url: ${H2_URL}
    driverClassName: org.h2.Driver
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}

  # JPA Configuration

  jpa:
    hibernate:
      show-sql: true
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true