# Application Global Properties for DEV and PROD configurations

  # Application Properties

spring:
  profiles:
    active: development
  config:
    import: optional:secrets.properties

  # SMTP Gmail Configuration

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Spring Security

security:
  basic:
    enabled: true

management:
  security:
    enabled: true

  # Hibernate Logs

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:descriptor:sql:BasicBinder: TRACE

  # Token Credentials

token:
  secretKey: ${TOKEN_SECRET_KEY}

  # Swagger UI

springdoc:
  swagger-ui.path: swagger-ui.html
  packagesToScan: com.haredev.library
  swagger-ui:
    enabled: true