# Application Global Properties for DEV and PROD configurations

  # Application Properties

spring:
  profiles:
      active: prod
  config:
    import: optional:secrets.properties

  # Spring Security

security:
  basic:
    enabled: true

management:
  security:
    enabled: true

  # Hibernate Logs

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:descriptor:sql:BasicBinder: TRACE

  # Token Credentials

token:
  secretKey: ${TOKEN_SECRET_KEY}

  # Swagger UI

springdoc:
  swagger-ui.path: swagger-ui.html
  packagesToScan: com.haredev.library
  swagger-ui:
    enabled: true