# Application PROD - profile properties

server:
    port: 9090

    # JPA/Hibernate/PostgreSQL Configuration

spring:
    show-sql: true
    generate-ddl: true
    hibernate:
        ddl-auto: create-drop
    properties:
        hibernate:format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect